version: '3.8'

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: sherlock
      POSTGRES_PASSWORD: password
      POSTGRES_DB: sherlockhums
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  server:
    build: ./server
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgres://sherlock:password@postgres:5432/sherlockhums?sslmode=disable

  client:
    build: ./client
    ports:
      - "5173:5173"
    depends_on:
      - server

volumes:
  pgdata:
