CREATE TABLE IF NOT EXISTS sessions (
  id VARCHAR(6) PRIMARY KEY,
  host_id INTEGER,
  state VARCHAR(20) NOT NULL DEFAULT 'WAITING',
  created_at TIMESTAMP NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMP NOT NULL DEFAULT NOW()
);